### PR TITLE
Upgraded to Guzzle 7

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
@cuonggt can this be reviewed?

**Comment by ghost** [comment]
Bump

**Comment by cuonggt** [comment]
> @cuonggt can this be reviewed?

Hi, could you just update guzzle version and keep the branch alias as before?

```
"dev-master": "1.0-dev"
```

**Comment by ghost** [comment]
@cuonggt done!

**Pull request merged**
